#!/bin/bash

# Unpack script arguments
argc="$#";: "$((i=0))"
while [ "$((i))" -lt "$argc" ]; do
  case "$1" in
    --nowarn|--nw) NoWarn='true';;
    *) files="$files $1";;
  esac
  shift;: "$((i=i+1))"
done

rand="$(date +%s)$(LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c10)"
cleanup() {
  rm -rf "$rand"
}
trap cleanup EXIT
if ! clang -Wall -Wextra $files -o "$rand"; then
  exit 1
fi
if [ ! "$NoWarn" ] && ! clang -Wall -Wextra -Werror $files -o "$rand" >/dev/null 2>&1; then
  read -p 'Warnings detected, proceed? (enter to proceed, n to abort) ' proceed
  if [ "$proceed" = 'n' ]; then
    printf 'aborted\n\n'
    exit 1
  fi
fi
echo
./"$rand"
